import { BillingRule } from '../types';

let _cachedToken: string | null = null;
let _locationId: string | null = null;
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

function getHeaders(): Record<string, string> {
    if (!_cachedToken) {
        console.warn('[BillingRuleService] ⚠️ No cached token! setAccessToken() should be called.');
    }
    return {
        'apikey': SUPABASE_KEY,
        'Authorization': `Bearer ${_cachedToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Prefer': 'return=representation'
    };
}

export const BillingRuleService = {
    setAccessToken(token: string) {
        _cachedToken = token;
        console.log('[BillingRuleService] 🔑 Access token cached');
    },

    clearAccessToken() {
        _cachedToken = null;
        console.log('[BillingRuleService] 🔒 Access token cleared');
    },

    setLocationId(id: string) {
        _locationId = id;
    },

    async getRules(): Promise<BillingRule[]> {
        console.log('[BillingRuleService] Fetching billing rules (REST)...');
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 45000);

        try {
            const response = await fetch(`${SUPABASE_URL}/rest/v1/billing_rules?select=*&order=created_at.desc`, {
                method: 'GET',
                headers: getHeaders(),
                signal: controller.signal
            });
            clearTimeout(timeoutId);

            if (!response.ok) {
                throw new Error(`REST Error ${response.status}: ${await response.text()}`);
            }

            const data = await response.json();
            return (data || []).map((r: any) => ({
                id: r.id,
                testName: r.test_name,
                cpt: r.cpt,
                insurers: Array.isArray(r.insurers) ? r.insurers : [],
                billToClient: r.bill_to_client
            }));
        } catch (error) {
            console.error('[BillingRuleService] Fetch failed:', error);
            return [];
        }
    },

    async createRule(rule: BillingRule): Promise<BillingRule | null> {
        console.log("[BillingRuleService] Creating (REST):", rule.testName);

        // Omit id if it's mock string generated by client (e.g. br_123)
        // Let the DB generate UUID if needed, otherwise use it if valid UUID
        const isUUID = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/.test(rule.id);

        const payload: any = {
            test_name: rule.testName,
            cpt: rule.cpt,
            insurers: rule.insurers || [],
            bill_to_client: rule.billToClient ?? true,
            updated_at: new Date().toISOString()
        };

        if (isUUID) {
            payload.id = rule.id;
        }

        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 45000);

        try {
            const response = await fetch(`${SUPABASE_URL}/rest/v1/billing_rules`, {
                method: 'POST',
                headers: getHeaders(),
                body: JSON.stringify(payload),
                signal: controller.signal
            });
            clearTimeout(timeoutId);

            if (!response.ok) {
                throw new Error(`Create Failed ${response.status}: ${await response.text()}`);
            }

            const data = await response.json();
            if (!data || data.length === 0) throw new Error('No data returned');

            return {
                id: data[0].id,
                testName: data[0].test_name,
                cpt: data[0].cpt,
                insurers: data[0].insurers,
                billToClient: data[0].bill_to_client
            };
        } catch (err) {
            console.error('[BillingRuleService] Create failed:', err);
            throw err;
        }
    },

    async updateRule(rule: BillingRule): Promise<BillingRule | null> {
        const payload = {
            test_name: rule.testName,
            cpt: rule.cpt,
            insurers: rule.insurers || [],
            bill_to_client: rule.billToClient ?? true,
            updated_at: new Date().toISOString()
        };

        try {
            const response = await fetch(`${SUPABASE_URL}/rest/v1/billing_rules?id=eq.${rule.id}`, {
                method: 'PATCH',
                headers: getHeaders(),
                body: JSON.stringify(payload)
            });

            if (!response.ok) throw new Error(`Update Failed ${response.status}`);
            const data = await response.json();

            if (!data || data.length === 0) return null;

            return {
                ...rule,
                id: data[0].id,
                testName: data[0].test_name,
                cpt: data[0].cpt,
                insurers: data[0].insurers,
                billToClient: data[0].bill_to_client
            };
        } catch (err) {
            console.error('[BillingRuleService] Update failed:', err);
            throw err;
        }
    },

    async deleteRule(id: string): Promise<boolean> {
        try {
            const response = await fetch(`${SUPABASE_URL}/rest/v1/billing_rules?id=eq.${id}`, {
                method: 'DELETE',
                headers: getHeaders()
            });
            return response.ok;
        } catch (err) {
            console.error('[BillingRuleService] Delete failed:', err);
            return false;
        }
    }
};
