import { PettyCashTransaction } from '../types';
import { supabase } from '../src/lib/supabase';

// In-memory token cache similar to other services
let _cachedToken: string | null = null;
let _locationId: string | null = null;

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

function getHeaders(): Record<string, string> {
    if (!_cachedToken) {
        console.error('[PettyCashService] ❌ No cached token! setAccessToken() was not called.');
    }
    return {
        'apikey': SUPABASE_KEY,
        'Authorization': `Bearer ${_cachedToken}`,
        'Content-Type': 'application/json',
        'Accept': 'application/json'
    };
}

export const PettyCashService = {
    setAccessToken(token: string) {
        _cachedToken = token;
        console.log('[PettyCashService] 🔑 Access token cached');
    },

    clearAccessToken() {
        _cachedToken = null;
        console.log('[PettyCashService] 🗑️ Access token cleared');
    },

    setLocationId(id: string) {
        _locationId = id;
        console.log('[PettyCashService] 📍 Location ID set:', id);
    },

    /**
     * Fetch Petty Cash transactions for the current location
     */
    async getTransactions(): Promise<PettyCashTransaction[]> {
        if (!_cachedToken) {
            console.warn('[PettyCashService] Cannot fetch transactions: No token');
            throw new Error('No token');
        }

        if (!_locationId) {
            console.warn('[PettyCashService] Cannot fetch transactions: No location_id');
            throw new Error('No location_id');
        }

        try {
            const url = `${SUPABASE_URL}/rest/v1/petty_cash_transactions?location_id=eq.${_locationId}&order=timestamp.desc`;
            
            const response = await fetch(url, {
                method: 'GET',
                headers: getHeaders()
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Failed to fetch petty cash: ${response.status} ${errText}`);
            }

            const data = await response.json();
            
            // Map DB format to App format
            return data.map((row: any) => ({
                id: row.id,
                userId: row.user_id,
                userName: row.user_name,
                amount: parseFloat(row.amount),
                action: row.action,
                reason: row.reason,
                runningBalance: parseFloat(row.running_balance),
                timestamp: row.timestamp
            }));
        } catch (error) {
            console.error('[PettyCashService] ❌ Error fetching petty cash:', error);
            throw error;
        }
    },

    /**
     * Add a new Petty Cash transaction
     */
    async addTransaction(transaction: Omit<PettyCashTransaction, 'id' | 'timestamp'>): Promise<PettyCashTransaction | null> {
        if (!_cachedToken || !_locationId) {
            throw new Error('Missing Auth Token or Location ID');
        }

        try {
            const dbData = {
                user_id: transaction.userId,
                user_name: transaction.userName,
                amount: transaction.amount,
                action: transaction.action,
                reason: transaction.reason,
                running_balance: transaction.runningBalance,
                location_id: _locationId
                // id and timestamp are generated by Postgres
            };

            const url = `${SUPABASE_URL}/rest/v1/petty_cash_transactions`;
            const response = await fetch(url, {
                method: 'POST',
                headers: {
                    ...getHeaders(),
                    'Prefer': 'return=representation'
                },
                body: JSON.stringify(dbData)
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Failed to save petty cash: ${response.status} ${errText}`);
            }

            const data = await response.json();
            if (data && data.length > 0) {
                const row = data[0];
                return {
                    id: row.id,
                    userId: row.user_id,
                    userName: row.user_name,
                    amount: parseFloat(row.amount),
                    action: row.action,
                    reason: row.reason,
                    runningBalance: parseFloat(row.running_balance),
                    timestamp: row.timestamp
                };
            }
            return null;
        } catch (error) {
            console.error('[PettyCashService] ❌ Error saving transaction:', error);
            throw error;
        }
    },

    /**
     * Update an existing Petty Cash transaction
     */
    async updateTransaction(id: string, updates: Partial<PettyCashTransaction>): Promise<boolean> {
        if (!_cachedToken || !_locationId) {
            throw new Error('Missing Auth Token or Location ID');
        }

        try {
            const dbData: any = {};
            if (updates.amount !== undefined) dbData.amount = updates.amount;
            if (updates.action !== undefined) dbData.action = updates.action;
            if (updates.reason !== undefined) dbData.reason = updates.reason;
            if (updates.runningBalance !== undefined) dbData.running_balance = updates.runningBalance;

            const url = `${SUPABASE_URL}/rest/v1/petty_cash_transactions?id=eq.${id}&location_id=eq.${_locationId}`;
            const response = await fetch(url, {
                method: 'PATCH',
                headers: getHeaders(),
                body: JSON.stringify(dbData)
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Failed to update petty cash: ${response.status} ${errText}`);
            }

            return true;
        } catch (error) {
            console.error('[PettyCashService] ❌ Error updating transaction:', error);
            throw error;
        }
    },

    /**
     * Delete a single Petty Cash transaction
     */
    async deleteTransaction(id: string): Promise<boolean> {
        if (!_cachedToken || !_locationId) {
            throw new Error('Missing Auth Token or Location ID');
        }

        try {
            const url = `${SUPABASE_URL}/rest/v1/petty_cash_transactions?id=eq.${id}&location_id=eq.${_locationId}`;
            const response = await fetch(url, {
                method: 'DELETE',
                headers: getHeaders()
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Failed to delete petty cash: ${response.status} ${errText}`);
            }

            return true;
        } catch (error) {
            console.error('[PettyCashService] ❌ Error deleting transaction:', error);
            throw error;
        }
    },

    /**
     * Clear all Petty Cash transactions for the location
     * (Called when "Limpiar Data" is selected)
     */
    async clearTransactions(): Promise<boolean> {
        if (!_cachedToken || !_locationId) {
            throw new Error('Missing Auth Token or Location ID');
        }

        try {
            const url = `${SUPABASE_URL}/rest/v1/petty_cash_transactions?location_id=eq.${_locationId}`;
            const response = await fetch(url, {
                method: 'DELETE',
                headers: getHeaders()
            });

            if (!response.ok) {
                const errText = await response.text();
                throw new Error(`Failed to clear petty cash: ${response.status} ${errText}`);
            }

            return true;
        } catch (error) {
            console.error('[PettyCashService] ❌ Error clearing petty cash:', error);
            throw error;
        }
    }
};
