
import React, { useState, useMemo, useRef } from 'react';
import { createPortal } from 'react-dom';
import { DailyReport } from '../types/dailyReport';
import { UserRole, Permission, User } from '../types';
import { formatDate, formatDateForFilename } from '../utils/dateUtils';
import { DailyReportService } from '../services/DailyReportService';

interface ReportHistoryProps {
    reports: DailyReport[];
    user: User;
    onEditReport: (report: DailyReport) => void;
    onDeleteReport: (id: string) => void;
    onViewReport: (report: DailyReport) => void; // Trigger PDF view
    onCreateNew: () => void;
}

type TimeFilter = 'this_month' | 'last_month' | 'this_quarter' | 'this_year' | 'custom';

// --- AGGREGATE REPORT DOCUMENT ---
const AggregateReportDocument: React.FC<{
    data: any;
    period: { start: Date; end: Date; label: string };
    reportCount: number;
    generatedBy: string;
}> = ({ data, period, reportCount, generatedBy }) => {

    const formatCurrency = (val: number) => `$${val.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

    return (
        <div
            className="bg-white text-slate-900 font-sans box-border relative leading-normal"
            style={{
                width: '215.9mm',
                minHeight: '279.4mm',
                margin: '0',
                padding: '0',
                backgroundColor: '#ffffff'
            }}
        >
            {/* Header Strip */}
            <div className="bg-slate-800 text-white px-12 py-8 flex justify-between items-center print-color-adjust" style={{ backgroundColor: '#1e293b', color: 'white', WebkitPrintColorAdjust: 'exact' }}>
                <div>
                    <h1 className="text-3xl font-black tracking-tight uppercase m-0 leading-none">
                        Health<span className="text-emerald-400" style={{ color: '#34d399' }}>Axis</span> Analytics
                    </h1>
                    <p className="text-[10px] font-bold tracking-[0.2em] uppercase text-slate-400 mt-2">
                        Period Summary Report
                    </p>
                </div>
                <div className="text-right">
                    <div className="text-[10px] font-bold text-slate-500 uppercase tracking-wider">Reports Included</div>
                    <div className="text-2xl font-mono font-bold text-white">{reportCount}</div>
                </div>
            </div>

            {/* Meta Bar */}
            <div className="bg-slate-100 border-b border-slate-200 px-12 py-3 flex justify-between text-[10px] uppercase font-bold tracking-wide text-slate-500" style={{ backgroundColor: '#f1f5f9', borderBottom: '1px solid #e2e8f0' }}>
                <div>Period: <span className="text-slate-900 ml-2">{formatDate(period.start)} — {formatDate(period.end)}</span></div>
                <div>Generated By: <span className="text-slate-900 ml-2">{generatedBy}</span></div>
                <div>Date: <span className="text-slate-900 ml-2">{formatDate(new Date())}</span></div>
            </div>

            <div className="p-12">
                {/* Executive Summary Cards */}
                <div className="flex justify-between gap-6 mb-10">
                    <div className="w-[32%] bg-slate-50 border border-slate-200 rounded-lg p-4" style={{ backgroundColor: '#f8fafc', border: '1px solid #e2e8f0' }}>
                        <div className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">Total Revenue</div>
                        <div className="text-3xl font-black text-slate-900 mt-1">{formatCurrency(data.totals.revenue)}</div>
                    </div>
                    <div className="w-[32%] bg-slate-50 border border-slate-200 rounded-lg p-4" style={{ backgroundColor: '#f8fafc', border: '1px solid #e2e8f0' }}>
                        <div className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">Total Patients</div>
                        <div className="text-3xl font-black text-slate-900 mt-1">{data.totals.patients}</div>
                    </div>
                    <div className="w-[32%] bg-slate-50 border border-slate-200 rounded-lg p-4" style={{ backgroundColor: '#f8fafc', border: '1px solid #e2e8f0' }}>
                        <div className="text-[9px] font-bold text-slate-400 uppercase tracking-wider">Avg. Daily Revenue</div>
                        <div className="text-3xl font-black text-emerald-600 mt-1">{formatCurrency(data.totals.revenue / (reportCount || 1))}</div>
                    </div>
                </div>

                {/* Section 1: Financials */}
                <div className="mb-10">
                    <div className="flex items-center gap-3 border-b-2 border-slate-900 pb-2 mb-4">
                        <div className="w-6 h-6 bg-slate-900 text-white flex items-center justify-center text-xs font-bold rounded" style={{ backgroundColor: '#0f172a', color: 'white' }}>1</div>
                        <h3 className="text-sm font-bold uppercase tracking-wide text-slate-900">Financial Totals</h3>
                    </div>

                    <div className="flex justify-between gap-10">
                        {/* Drawer */}
                        <div className="w-[48%]">
                            <table className="w-full text-xs border-collapse">
                                <thead>
                                    <tr className="border-b border-slate-300">
                                        <th className="text-left py-2 font-bold text-slate-500 uppercase">Drawer Method</th>
                                        <th className="text-right py-2 font-bold text-slate-500 uppercase">Total Amount</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {Object.entries(data.financials.methods).map(([k, v]) => (
                                        <tr key={k} className="border-b border-slate-100">
                                            <td className="py-2 font-medium capitalize text-slate-700">{k}</td>
                                            <td className="py-2 text-right font-mono font-bold text-slate-900">{formatCurrency(v as number)}</td>
                                        </tr>
                                    ))}
                                    <tr className="bg-slate-50" style={{ backgroundColor: '#f8fafc' }}>
                                        <td className="py-3 font-bold text-slate-900">TOTAL DRAWER</td>
                                        <td className="py-3 text-right font-black text-slate-900 text-sm">
                                            {formatCurrency((Object.values(data.financials.methods) as number[]).reduce((a, b) => a + b, 0))}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {/* System */}
                        <div className="w-[48%]">
                            <table className="w-full text-xs border-collapse">
                                <thead>
                                    <tr className="border-b border-slate-300">
                                        <th className="text-left py-2 font-bold text-slate-500 uppercase">System Posting</th>
                                        <th className="text-right py-2 font-bold text-slate-500 uppercase">Total Amount</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {Object.entries(data.financials.types).map(([k, v]) => (
                                        <tr key={k} className="border-b border-slate-100">
                                            <td className="py-2 font-medium capitalize text-slate-700">{k.replace(/([A-Z])/g, ' $1').trim()}</td>
                                            <td className="py-2 text-right font-mono font-bold text-slate-900">{formatCurrency(v as number)}</td>
                                        </tr>
                                    ))}
                                    <tr className="bg-slate-50" style={{ backgroundColor: '#f8fafc' }}>
                                        <td className="py-3 font-bold text-slate-900">TOTAL POSTED</td>
                                        <td className="py-3 text-right font-black text-slate-900 text-sm">
                                            {formatCurrency((Object.values(data.financials.types) as number[]).reduce((a, b) => a + b, 0))}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                {/* Section 2: Volume & Stats */}
                <div className="flex justify-between gap-10 mb-10">
                    <div className="w-[48%]">
                        <div className="flex items-center gap-3 border-b-2 border-slate-900 pb-2 mb-4">
                            <div className="w-6 h-6 bg-slate-900 text-white flex items-center justify-center text-xs font-bold rounded" style={{ backgroundColor: '#0f172a', color: 'white' }}>2</div>
                            <h3 className="text-sm font-bold uppercase tracking-wide text-slate-900">Patient Volume</h3>
                        </div>
                        <table className="w-full text-xs border-collapse">
                            <tbody>
                                {Object.entries(data.insurances).map(([k, v]) => (
                                    <tr key={k} className="border-b border-slate-100">
                                        <td className="py-2 text-slate-600 capitalize">{k.replace(/_/g, ' ').replace('Comp', ' Comp')}</td>
                                        <td className="py-2 text-right font-bold text-slate-900">{v as number}</td>
                                    </tr>
                                ))}
                                <tr className="bg-slate-50 border-t border-slate-200" style={{ backgroundColor: '#f8fafc' }}>
                                    <td className="py-2 font-bold text-slate-900">TOTAL PATIENTS</td>
                                    <td className="py-2 text-right font-black text-slate-900 text-sm">{data.totals.patients}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div className="w-[48%] flex flex-col gap-6">
                        <div>
                            <div className="flex items-center gap-3 border-b-2 border-slate-900 pb-2 mb-4">
                                <div className="w-6 h-6 bg-slate-900 text-white flex items-center justify-center text-xs font-bold rounded" style={{ backgroundColor: '#0f172a', color: 'white' }}>3</div>
                                <h3 className="text-sm font-bold uppercase tracking-wide text-slate-900">Operational Stats</h3>
                            </div>
                            <div className="bg-slate-50 rounded-lg p-4 border border-slate-100" style={{ backgroundColor: '#f8fafc', border: '1px solid #f1f5f9' }}>
                                <div className="flex justify-between text-xs mb-3">
                                    <span className="font-bold text-slate-700">Total Nurse Visits</span>
                                    <span className="font-bold text-slate-900">{data.operational.nurseVisits}</span>
                                </div>
                                <div className="flex justify-between text-xs mb-3">
                                    <span className="font-bold text-slate-700">New Patients</span>
                                    <span className="font-bold text-slate-900">{data.stats.newPts}</span>
                                </div>
                                <div className="flex justify-between text-xs mb-3">
                                    <span className="font-bold text-slate-700">Established</span>
                                    <span className="font-bold text-slate-900">{data.stats.estPts}</span>
                                </div>
                                <div className="flex justify-between text-xs mb-1">
                                    <span className="font-bold text-slate-700">X-Rays Performed</span>
                                    <span className="font-bold text-slate-900">{data.stats.xrays}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="mt-8 pt-8 border-t border-slate-200 text-[9px] text-center text-slate-400 font-medium uppercase tracking-wider">
                    Confidential Internal Document • HealthAxis Inventory System
                </div>
            </div>
        </div>
    );
};


const ReportHistory: React.FC<ReportHistoryProps> = ({ reports, user, onEditReport, onDeleteReport, onViewReport, onCreateNew }) => {
    const [filterType, setFilterType] = useState<TimeFilter>('this_month');
    const [startDate, setStartDate] = useState('');
    const [endDate, setEndDate] = useState('');
    const aggregateRef = useRef<HTMLDivElement>(null);

    // Filtering Logic
    const { filteredReports, range } = useMemo(() => {
        const now = new Date();
        let start = new Date(0); // Epoch
        let end = new Date(); // Now

        if (filterType === 'this_month') {
            start = new Date(now.getFullYear(), now.getMonth(), 1);
            end = new Date(now.getFullYear(), now.getMonth() + 1, 0);
            end.setHours(23, 59, 59, 999);
        } else if (filterType === 'last_month') {
            start = new Date(now.getFullYear(), now.getMonth() - 1, 1);
            end = new Date(now.getFullYear(), now.getMonth(), 0);
            end.setHours(23, 59, 59, 999);
        } else if (filterType === 'this_quarter') {
            const quarter = Math.floor((now.getMonth() + 3) / 3);
            start = new Date(now.getFullYear(), (quarter - 1) * 3, 1);
            end = new Date(now.getFullYear(), quarter * 3, 0);
            end.setHours(23, 59, 59, 999);
        } else if (filterType === 'this_year') {
            start = new Date(now.getFullYear(), 0, 1);
            end = new Date(now.getFullYear(), 11, 31);
            end.setHours(23, 59, 59, 999);
        } else if (filterType === 'custom' && startDate && endDate) {
            start = new Date(startDate);
            end = new Date(endDate);
            end.setHours(23, 59, 59, 999);
        }

        console.log('[ReportHistory] Filtering reports:', reports.length, 'Type:', filterType);

        const filtered = reports.filter(r => {
            const rDate = new Date(r.timestamp);
            const inRange = rDate >= start && rDate <= end;
            if (!inRange) console.log('[ReportHistory] Filtered out:', r.id, r.timestamp, 'Range:', start.toISOString(), '-', end.toISOString());
            return inRange;
        }).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

        console.log('[ReportHistory] Filtered count:', filtered.length);
        return { filteredReports: filtered, range: { start, end, label: filterType } };
    }, [reports, filterType, startDate, endDate]);

    // Aggregation Logic
    const aggregatedData = useMemo(() => {
        const initial = {
            financials: { methods: { cash: 0, credit: 0, check: 0 }, types: { billPay: 0, copay: 0, selfPay: 0 } },
            insurances: { medicaid: 0, bcbs_il: 0, meridian: 0, commercial: 0, medicare: 0, workersComp: 0, selfPay: 0 },
            operational: { nurseVisits: 0, providerVisits: {} as Record<string, number> },
            stats: { newPts: 0, estPts: 0, xrays: 0 },
            totals: { revenue: 0, patients: 0 }
        };

        return filteredReports.reduce((acc, report) => {
            // Financials
            acc.financials.methods.cash += report.financials.methods.cash || 0;
            acc.financials.methods.credit += report.financials.methods.credit || 0;
            acc.financials.methods.check += report.financials.methods.check || 0;
            acc.financials.types.billPay += report.financials.types.billPay || 0;
            acc.financials.types.copay += report.financials.types.copay || 0;
            acc.financials.types.selfPay += report.financials.types.selfPay || 0;

            // Insurances
            Object.keys(acc.insurances).forEach(k => {
                const key = k as keyof typeof acc.insurances;
                acc.insurances[key] += report.insurances[key] || 0;
            });

            // Operational
            acc.operational.nurseVisits += report.operational.nurseVisits || 0;

            // Stats
            acc.stats.newPts += report.stats.newPts || 0;
            acc.stats.estPts += report.stats.estPts || 0;
            acc.stats.xrays += report.stats.xrays || 0;

            // Totals
            acc.totals.revenue += report.totals.revenue || 0;
            acc.totals.patients += report.totals.patients || 0;

            return acc;
        }, initial);
    }, [filteredReports]);

    // Generate Aggregate PDF
    const handleGenerateSummary = () => {
        if (filteredReports.length === 0) {
            alert("No reports found in the selected period to summarize.");
            return;
        }
        if (!aggregateRef.current || !(window as any).html2pdf) {
            alert("PDF generator not ready.");
            return;
        }

        const opt = {
            margin: 0,
            filename: `Period_Summary_${formatDateForFilename(range.start)}_to_${formatDateForFilename(range.end)}.pdf`,
            image: { type: 'jpeg', quality: 1.0 },
            html2canvas: {
                scale: 2,
                useCORS: true,
                scrollY: 0,
                scrollX: 0,
                windowWidth: 816,
                width: 816,
                x: 0,
                y: 0
            },
            jsPDF: { unit: 'mm', format: 'letter', orientation: 'portrait' }
        };

        (window as any).html2pdf().set(opt).from(aggregateRef.current).save();
    };

    const totalRevenue = aggregatedData.totals.revenue;
    const totalPatients = aggregatedData.totals.patients;

    return (
        <div className="space-y-8 pb-20 animate-fade-in-up">
            <header className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                <div>
                    <h2 className="text-4xl font-black text-gray-900 dark:text-white tracking-tight">Report History</h2>
                    <p className="text-gray-500 dark:text-gray-400 mt-2 text-lg">Daily Close Archive & Analytics</p>
                </div>
                <button
                    onClick={onCreateNew}
                    className="h-14 px-6 bg-medical-600 hover:bg-medical-500 text-white rounded-2xl font-bold shadow-lg flex items-center gap-2 transition-all transform hover:scale-105"
                >
                    <i className="fa-solid fa-plus"></i> New Daily Close
                </button>
            </header>

            {/* Control Bar */}
            <div className="bg-white dark:bg-gray-900 p-6 rounded-3xl shadow-sm border border-gray-100 dark:border-gray-800 flex flex-col xl:flex-row gap-6 items-center justify-between">
                {/* Filters */}
                <div className="flex flex-wrap gap-2">
                    {[
                        { id: 'this_month', label: 'This Month' },
                        { id: 'last_month', label: 'Last Month' },
                        { id: 'this_quarter', label: 'This Quarter' },
                        { id: 'this_year', label: 'YTD' },
                        { id: 'custom', label: 'Custom' },
                    ].map(f => (
                        <button
                            key={f.id}
                            onClick={() => setFilterType(f.id as TimeFilter)}
                            className={`px-4 py-2 rounded-xl text-sm font-bold transition-colors ${filterType === f.id
                                ? 'bg-gray-900 text-white dark:bg-white dark:text-gray-900'
                                : 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 hover:bg-gray-200'
                                }`}
                        >
                            {f.label}
                        </button>
                    ))}
                </div>

                {filterType === 'custom' && (
                    <div className="flex gap-4 items-center bg-gray-50 dark:bg-gray-800 p-2 rounded-xl">
                        <input type="date" value={startDate} onChange={e => setStartDate(e.target.value)} className="bg-transparent text-sm font-bold text-gray-700 dark:text-white outline-none" />
                        <span className="text-gray-400">-</span>
                        <input type="date" value={endDate} onChange={e => setEndDate(e.target.value)} className="bg-transparent text-sm font-bold text-gray-700 dark:text-white outline-none" />
                    </div>
                )}

                {/* Aggregates & Action */}
                <div className="flex gap-8 border-l border-gray-200 dark:border-gray-700 pl-8 items-center">
                    <div>
                        <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Total Revenue</div>
                        <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400">${totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2 })}</div>
                    </div>
                    <div className="mr-4">
                        <div className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Total Patients</div>
                        <div className="text-2xl font-black text-blue-600 dark:text-blue-400">{totalPatients}</div>
                    </div>

                    <button
                        onClick={handleGenerateSummary}
                        className="h-12 px-5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold shadow-md shadow-indigo-500/20 flex items-center gap-2 transition-all hover:-translate-y-0.5"
                        title="Generate summarized PDF for selected period"
                    >
                        <i className="fa-solid fa-file-invoice-dollar"></i> Generate Period Summary
                    </button>
                </div>
            </div>

            {/* Data Table */}
            <div className="glass-panel rounded-[2.5rem] shadow-glass overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-left">
                        <thead className="bg-gray-50/50 dark:bg-gray-800/50 border-b border-gray-100 dark:border-gray-800">
                            <tr>
                                <th className="p-6 text-xs font-extrabold text-gray-400 uppercase tracking-wider">Date / ID</th>
                                <th className="p-6 text-xs font-extrabold text-gray-400 uppercase tracking-wider">Author</th>
                                <th className="p-6 text-xs font-extrabold text-gray-400 uppercase tracking-wider">Financials</th>
                                <th className="p-6 text-xs font-extrabold text-gray-400 uppercase tracking-wider">Patients</th>
                                <th className="p-6 text-xs font-extrabold text-gray-400 uppercase tracking-wider text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100 dark:divide-gray-800/50">
                            {filteredReports.map(report => (
                                <tr key={report.id} className="hover:bg-gray-50 dark:hover:bg-gray-800/30 transition-colors">
                                    <td className="p-6">
                                        <div className="font-bold text-gray-900 dark:text-white">
                                            {formatDate(report.timestamp)}
                                        </div>
                                        <div className="text-xs text-gray-400 font-mono mt-1">#{report.id.slice(-8)}</div>
                                    </td>
                                    <td className="p-6">
                                        <div className="flex items-center gap-2">
                                            <div className="w-6 h-6 rounded-full bg-indigo-100 text-indigo-600 dark:bg-indigo-900/30 dark:text-indigo-400 flex items-center justify-center text-xs font-bold">
                                                {report.author.charAt(0).toUpperCase()}
                                            </div>
                                            <span className="text-sm font-bold text-gray-600 dark:text-gray-300">{report.author}</span>
                                        </div>
                                    </td>
                                    <td className="p-6">
                                        <span className="font-mono font-bold text-emerald-600 dark:text-emerald-400">
                                            ${report.totals.revenue.toFixed(2)}
                                        </span>
                                    </td>
                                    <td className="p-6">
                                        <span className="font-bold text-gray-700 dark:text-gray-300">{report.totals.patients}</span>
                                    </td>
                                    <td className="p-6 text-right">
                                        <div className="flex justify-end gap-2">
                                            <button
                                                onClick={() => onViewReport(report)}
                                                className="w-10 h-10 rounded-xl bg-gray-100 dark:bg-gray-800 hover:bg-emerald-500 hover:text-white text-gray-500 transition-colors flex items-center justify-center"
                                                title="View PDF"
                                            >
                                                <i className="fa-solid fa-file-pdf"></i>
                                            </button>
                                            <button
                                                onClick={() => onEditReport(report)}
                                                className="w-10 h-10 rounded-xl bg-gray-100 dark:bg-gray-800 hover:bg-blue-500 hover:text-white text-gray-500 transition-colors flex items-center justify-center"
                                                title="Edit Details"
                                            >
                                                <i className="fa-solid fa-pen-to-square"></i>
                                            </button>
                                            <button
                                                onClick={() => { if (window.confirm('Delete this report history?')) onDeleteReport(report.id) }}
                                                className="w-10 h-10 rounded-xl bg-gray-100 dark:bg-gray-800 hover:bg-red-500 hover:text-white text-gray-500 transition-colors flex items-center justify-center"
                                                title="Delete Report"
                                            >
                                                <i className="fa-solid fa-trash"></i>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                            {filteredReports.length === 0 && (
                                <tr>
                                    <td colSpan={5} className="p-12 text-center text-gray-400 font-medium">
                                        No reports found for this period.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* --- HIDDEN AGGREGATE REPORT CONTAINER --- */}
            {createPortal(
                <div style={{ position: 'absolute', top: 0, left: '-10000px', width: '215.9mm', zIndex: -9999, pointerEvents: 'none' }}>
                    <div ref={aggregateRef}>
                        <AggregateReportDocument
                            data={aggregatedData}
                            period={range}
                            reportCount={filteredReports.length}
                            generatedBy={user.username}
                        />
                    </div>
                </div>,
                document.body
            )}
        </div>
    );
};

export default ReportHistory;
