import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { Resend } from 'npm:resend'
import { encode } from 'https://deno.land/std@0.168.0/encoding/base64.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY') || '';
const resend = new Resend(RESEND_API_KEY);

// Helper to generate VTIMEZONE block for common US timezones
const getTimezoneComponent = (tz: string): string[] => {
  let stdOffset = '-0500'
  let dstOffset = '-0400'
  let hasDst = true
  let stdName = 'EST'
  let dstName = 'EDT'
  
  if (tz === 'America/Chicago') {
    stdOffset = '-0600'
    dstOffset = '-0500'
    stdName = 'CST'
    dstName = 'CDT'
  } else if (tz === 'America/Denver') {
    stdOffset = '-0700'
    dstOffset = '-0600'
    stdName = 'MST'
    dstName = 'MDT'
  } else if (tz === 'America/Los_Angeles') {
    stdOffset = '-0800'
    dstOffset = '-0700'
    stdName = 'PST'
    dstName = 'PDT'
  } else if (tz === 'America/Phoenix') {
    stdOffset = '-0700'
    stdOffset = '-0700'
    stdName = 'MST'
    hasDst = false
  }
  
  const rules = [
    'BEGIN:VTIMEZONE',
    `TZID:${tz}`,
    `X-LIC-LOCATION:${tz}`,
  ]
  
  if (hasDst) {
    rules.push(
      'BEGIN:DAYLIGHT',
      `TZOFFSETFROM:${stdOffset}`,
      `TZOFFSETTO:${dstOffset}`,
      `TZNAME:${dstName}`,
      'DTSTART:19700308T020000',
      'RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU',
      'END:DAYLIGHT',
      'BEGIN:STANDARD',
      `TZOFFSETFROM:${dstOffset}`,
      `TZOFFSETTO:${stdOffset}`,
      `TZNAME:${stdName}`,
      'DTSTART:19701101T020000',
      'RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU',
      'END:STANDARD'
    )
  } else {
    rules.push(
      'BEGIN:STANDARD',
      `TZOFFSETFROM:${stdOffset}`,
      `TZOFFSETTO:${stdOffset}`,
      `TZNAME:${stdName}`,
      'DTSTART:19700101T000000',
      'END:STANDARD'
    )
  }
  
  rules.push('END:VTIMEZONE')
  return rules
}

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const payload = await req.json()
    const { type, data } = payload
    
    // Management emails that should receive all critical system notifications
    const managementEmails = ['manager@healthaxismgmt.com', 'smuza96@yahoo.com'];
    
    // Parse the requested 'to' addresses
    let toArray: string[] = [];
    if (payload.to) {
        toArray = typeof payload.to === 'string' ? [payload.to] : payload.to;
    } else {
        toArray = ['iarejyero@gmail.com'];
    }
    
    // Always append management emails to the recipient list (except for private calendar sync)
    if (type !== 'calendar_sync') {
        managementEmails.forEach(email => {
            if (!toArray.includes(email)) toArray.push(email);
        });
    }
    
    let to = toArray;
    let subject = 'Norvexis Core System';
    let html = '<p>Automated system message.</p>';
    let attachments: any[] = [];

    if (type === 'schedule_change') {
       subject = `[Norvexis] Schedule Update Notification`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #4f46e5;">Schedule Update</h2>
            <p>Hello,</p>
            <p>Changes have been made to your assigned schedule. Please review the Norvexis Core platform for more details.</p>
            ${data && data.date ? `<div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;"><p style="margin:0 0 10px 0;"><strong>Date:</strong> ${data.date}</p><p style="margin:0 0 10px 0;"><strong>Time:</strong> ${data.start_time} - ${data.end_time}</p><p style="margin:0;"><strong>Role:</strong> ${data.role_type || 'Staff'}</p></div>` : ''}
            <p style="color: #666; font-size: 12px; margin-top: 40px;">This is an automated message generated by the system.</p>
        </div>
       `;

       if (data && data.date && data.start_time && data.end_time) {
           try {
               let timezone = 'America/New_York'
               if (data.userId) {
                   try {
                       const supabaseAdmin = createClient(
                           Deno.env.get('SUPABASE_URL') ?? '',
                           Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
                       )
                       
                       const { data: assignment } = await supabaseAdmin
                           .from('user_location_assignments')
                           .select('location_id')
                           .eq('user_id', data.userId)
                           .eq('is_default', true)
                           .limit(1)
                           .maybeSingle()

                       const targetLocationId = assignment?.location_id
                       if (targetLocationId) {
                           const { data: loc } = await supabaseAdmin
                               .from('clinic_locations')
                               .select('timezone')
                               .eq('id', targetLocationId)
                               .limit(1)
                               .maybeSingle()
                           if (loc?.timezone) {
                               timezone = loc.timezone
                           }
                       } else {
                           const { data: loc } = await supabaseAdmin
                               .from('clinic_locations')
                               .select('timezone')
                               .limit(1)
                               .maybeSingle()
                           if (loc?.timezone) {
                               timezone = loc.timezone
                           }
                       }
                   } catch (tzErr) {
                       console.error('[send-email] Failed to resolve timezone, defaulting to America/New_York:', tzErr)
                   }
               }

               const formatDT = (dateStr: string, timeStr: string) => {
                   return `${dateStr.replace(/-/g, '')}T${timeStr.replace(/:/g, '')}00`;
               };
               
               const dtStart = formatDT(data.date, data.start_time);
               const dtEnd = formatDT(data.date, data.end_time);
               
               const icsString = [
                   'BEGIN:VCALENDAR',
                   'VERSION:2.0',
                   'PRODID:-//Norvexis//Core//EN',
                   'CALSCALE:GREGORIAN',
                   ...getTimezoneComponent(timezone),
                   'BEGIN:VEVENT',
                   `SUMMARY:Norvexis Shift - ${data.role_type || 'Staff'}`,
                   `DTSTART;TZID=${timezone}:${dtStart}`,
                   `DTEND;TZID=${timezone}:${dtEnd}`,
                   `DESCRIPTION:Norvexis Core Scheduled Shift. ${data.notes || ''}`,
                   'END:VEVENT',
                   'END:VCALENDAR'
               ].join('\r\n');
               
               const encoder = new TextEncoder();
               const base64Content = encode(encoder.encode(icsString));
               attachments.push({
                   filename: 'invite.ics',
                   content: base64Content
               });
           } catch (e) {
               console.error('[send-email] Failed to generate ICS:', e);
           }
       }
    } else if (type === 'inventory_alert') {
       subject = `[Norvexis] LOW STOCK ALERT: ${data.name}`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #dc2626;">Low Inventory Alert</h2>
            <p>The following product has dropped to an inventory level that requires attention:</p>
            <ul>
                <li><strong>Product:</strong> ${data.name}</li>
                <li><strong>Current Stock:</strong> <span style="color:#dc2626; font-weight:bold;">${data.stock}</span></li>
                <li><strong>Configured Minimum:</strong> ${data.min_stock || data.minStock}</li>
                <li><strong>Location ID:</strong> ${data.location_id || 'Main'}</li>
            </ul>
        </div>
       `;
    } else if (type === 'expiry_alert') {
       subject = `[Norvexis] EXPIRATION ALERT: Products expiring soon`;
       const itemsHtml = data.items.map((i: any) => `<li><strong>${i.name}</strong> - Expires on: ${i.expiry_date || i.expiryDate} (${i.stock} units remaining)</li>`).join('');
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #eab308;">Expiration Alert (30 Days)</h2>
            <p>The following inventory batches will expire in 30 days or less:</p>
            <ul>${itemsHtml}</ul>
            <p>Please ensure they are used or relocated according to the inventory protocol.</p>
        </div>
       `;
    } else if (type === 'test') {
       subject = '[Norvexis] Successful Integration Test';
       html = `<div style="font-family: sans-serif; padding: 20px;"><h2>Successful Connection!</h2><p>The notification system is operating optimally.</p></div>`
    } else if (type === 'daily_close') {
       subject = `[Norvexis] Daily Close Report - ${data.date || new Date().toLocaleDateString()}`;
       
       let downloadLinkHtml = '';
       if (data.pdfUrl) {
           downloadLinkHtml = `<p style="margin-top:20px; font-size:16px;"><strong>📎 <a href="${data.pdfUrl}" target="_blank" style="color: #4f46e5; text-decoration: none;">Download PDF Report</a></strong></p>`;
       }

       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #0f172a;">Daily Medical Close Complete</h2>
            <p>The daily close reconciliation has been completed via Norvexis Core.</p>
            <ul>
                <li><strong>Revenue:</strong> $${data.totalMethods || '0.00'}</li>
                <li><strong>Total Patients:</strong> ${data.totalInsurance || '0'}</li>
                <li><strong>Closed By:</strong> ${data.closedBy || 'Admin'}</li>
            </ul>
            <p>The official PDF report is attached to this email.</p>
            ${downloadLinkHtml}
        </div>
       `;
       
       if (data.pdfUrl) {
           try {
               const pdfRes = await fetch(data.pdfUrl);
               const pdfBuffer = await pdfRes.arrayBuffer();
               const base64Content = encode(new Uint8Array(pdfBuffer));
               attachments.push({
                   filename: `DailyClose_${data.date ? data.date.replace(/\//g, '-') : 'Report'}.pdf`,
                   content: base64Content
               });
           } catch (e) {
               console.error('[send-email] Failed to fetch PDF from URL:', e);
           }
       } else if (data.pdfBase64) {
           attachments.push({
               filename: `DailyClose_${data.date ? data.date.replace(/\//g, '-') : 'Report'}.pdf`,
               content: data.pdfBase64
           });
       }
    } else if (type === 'calendar_sync') {
        const supabaseUrl = Deno.env.get('SUPABASE_URL') || '';
        const cleanUrl = supabaseUrl.replace('https://', '');
        const googleUrl = `https://${cleanUrl}/functions/v1/calendar-feed?user_id=${data.userId}`;
        const appleUrl = `webcal://${cleanUrl}/functions/v1/calendar-feed?user_id=${data.userId}`;

        subject = `[Norvexis] Workforce Schedule Calendar Subscription`;
        html = `
         <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
             <div style="text-align: center; margin-bottom: 24px;">
                 <h2 style="color: #4f46e5; margin: 0; font-size: 22px; font-weight: 700;">Norvexis Workforce Schedule Sync</h2>
                 <p style="color: #64748b; font-size: 14px; margin-top: 4px;">Synchronize your shifts with your personal device calendar</p>
             </div>
             
             <p style="font-size: 16px; color: #1e293b; line-height: 1.5; margin-bottom: 16px;">Hello <strong>${data.name}</strong>,</p>
             <p style="font-size: 15px; color: #334155; line-height: 1.5; margin-bottom: 24px;">Your manager has generated a direct calendar synchronization link for you. This allows you to subscribe to your work shifts and see them update automatically in Google Calendar, Apple Calendar, or Outlook.</p>
             
             <div style="margin-bottom: 28px;">
                 <h3 style="color: #0f172a; font-size: 16px; margin: 0 0 12px 0; border-bottom: 1px solid #f1f5f9; padding-bottom: 6px;">Calendar Setup Options</h3>
                 
                 <!-- Apple Calendar -->
                 <div style="background-color: #f8fafc; border-left: 4px solid #007aff; padding: 14px; border-radius: 4px; margin-bottom: 16px;">
                     <h4 style="margin: 0 0 6px 0; color: #007aff; font-size: 15px;">Option 1: Apple Calendar (iPhone, iPad, Mac)</h4>
                     <p style="margin: 0 0 10px 0; font-size: 13px; color: #475569; line-height: 1.4;">Click the button below to subscribe directly on your Apple device calendar.</p>
                     <a href="${appleUrl}" style="display: inline-block; background-color: #007aff; color: #ffffff; text-decoration: none; padding: 8px 16px; font-size: 13px; font-weight: bold; border-radius: 6px;">Subscribe on Apple Calendar</a>
                 </div>

                 <!-- Google Calendar -->
                 <div style="background-color: #f8fafc; border-left: 4px solid #34a853; padding: 14px; border-radius: 4px;">
                     <h4 style="margin: 0 0 6px 0; color: #34a853; font-size: 15px;">Option 2: Google Calendar (Android, Web)</h4>
                     <p style="margin: 0 0 10px 0; font-size: 13px; color: #475569; line-height: 1.4;">Copy the link below, open Google Calendar in a browser, click <strong>+ Add Calendar</strong> -> <strong>From URL</strong>, and paste this link:</p>
                     <div style="background-color: #ffffff; border: 1px dashed #cbd5e1; padding: 8px; border-radius: 4px; font-family: monospace; font-size: 11px; word-break: break-all; color: #334155; margin-bottom: 10px;">
                         ${googleUrl}
                     </div>
                     <a href="${googleUrl}" target="_blank" style="display: inline-block; background-color: #34a853; color: #ffffff; text-decoration: none; padding: 8px 16px; font-size: 13px; font-weight: bold; border-radius: 6px;">Open Feed Link</a>
                 </div>
             </div>
             
             <p style="font-size: 13px; color: #64748b; line-height: 1.5; margin-top: 24px; border-top: 1px solid #f1f5f9; padding-top: 16px;">
                 <strong>Note:</strong> Changes made by your manager on the scheduler will automatically sync to your calendar, although updates may take some hours to appear depending on your calendar application's synchronization frequency.
             </p>
         </div>
        `;
     } else if (type === 'schedule_summary') {
         const supabaseUrl = Deno.env.get('SUPABASE_URL') || '';
         const cleanUrl = supabaseUrl.replace('https://', '');
         const googleUrl = `https://${cleanUrl}/functions/v1/calendar-feed?user_id=${data.userId}`;
         const appleUrl = `webcal://${cleanUrl}/functions/v1/calendar-feed?user_id=${data.userId}`;

         subject = `[Norvexis] Workforce Schedule Summary - ${data.monthName}`;
         
         const shiftsHtml = data.shifts && data.shifts.length > 0
             ? data.shifts.map((s: any) => `
                 <tr style="border-bottom: 1px solid #e2e8f0;">
                     <td style="padding: 10px 0; font-size: 14px; color: #334155;"><strong>${s.date}</strong></td>
                     <td style="padding: 10px 0; font-size: 14px; color: #334155; text-align: right;">${s.start_time} - ${s.end_time}</td>
                 </tr>
             `).join('')
             : '<tr><td colspan="2" style="padding: 15px 0; text-align: center; color: #64748b; font-style: italic;">No shifts scheduled for this period.</td></tr>';
             
         html = `
          <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
              <div style="text-align: center; border-bottom: 2px solid #4f46e5; padding-bottom: 16px; margin-bottom: 20px;">
                  <h2 style="color: #4f46e5; margin: 0; font-size: 22px; font-weight: 700;">Immediate Care Plus</h2>
                  <p style="color: #64748b; font-size: 14px; margin-top: 4px;">Your Work Schedule for ${data.monthName}</p>
              </div>
              
              <p style="font-size: 16px; color: #1e293b; line-height: 1.5; margin-bottom: 16px;">Hello <strong>${data.name}</strong>,</p>
              <p style="font-size: 15px; color: #334155; line-height: 1.5; margin-bottom: 20px;">The schedule for <strong>${data.monthName}</strong> has been finalized. Below is a summary of your assigned shifts and hours.</p>
              
              <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
                  <thead>
                      <tr style="border-bottom: 2px solid #cbd5e1; text-align: left;">
                          <th style="padding-bottom: 8px; font-size: 13px; text-transform: uppercase; color: #475569; letter-spacing: 0.05em;">Date</th>
                          <th style="padding-bottom: 8px; font-size: 13px; text-transform: uppercase; color: #475569; letter-spacing: 0.05em; text-align: right;">Hours</th>
                      </tr>
                  </thead>
                  <tbody>
                      ${shiftsHtml}
                  </tbody>
                  <tfoot>
                      <tr style="border-top: 2px solid #cbd5e1; font-weight: bold;">
                          <td style="padding-top: 12px; font-size: 15px; color: #0f172a;">Total Scheduled Hours</td>
                          <td style="padding-top: 12px; font-size: 15px; color: #0f172a; text-align: right;">${data.totalHours} hrs</td>
                      </tr>
                  </tfoot>
              </table>
              
              <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-top: 24px;">
                  <h4 style="margin: 0 0 8px 0; color: #4f46e5; font-size: 15px;">Subscribe to your calendar</h4>
                  <p style="margin: 0 0 12px 0; font-size: 13px; color: #475569; line-height: 1.4;">Add this schedule to your phone or Google calendar to see automatic updates.</p>
                  <div style="margin-top: 10px;">
                      <a href="${appleUrl}" style="display: inline-block; background-color: #007aff; color: #ffffff; text-decoration: none; padding: 8px 16px; font-size: 13px; font-weight: bold; border-radius: 6px; margin-right: 8px;">Subscribe on iPhone</a>
                      <a href="${googleUrl}" target="_blank" style="display: inline-block; background-color: #34a853; color: #ffffff; text-decoration: none; padding: 8px 16px; font-size: 13px; font-weight: bold; border-radius: 6px;">Add to Google Calendar</a>
                  </div>
              </div>
              
              <p style="color: #64748b; font-size: 12px; margin-top: 30px; border-top: 1px solid #f1f5f9; padding-top: 15px; text-align: center;">This is an automated message. For questions or modifications, please contact your supervisor.</p>
          </div>
         `;
     }

    console.log(`[send-email] Sending ${type} email to ${to}`);

    const { data: emailData, error } = await resend.emails.send({
      from: 'Norvexis Core <noreply@norvexiscore.com>',
      to: typeof to === 'string' ? [to] : to,
      subject,
      html,
      attachments: attachments.length > 0 ? attachments : undefined,
    });

    if (error) {
      console.error("[send-email] Error sending resend:", error);
      return new Response(JSON.stringify({ error }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      });
    }

    return new Response(JSON.stringify(emailData), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });
  } catch (error: any) {
    console.error("[send-email] Exception:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    });
  }
})
