import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { Resend } from 'npm:resend'
import { encode } from 'https://deno.land/std@0.168.0/encoding/base64.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const RESEND_API_KEY = "re_6H9Qq4rL_8U485mAfZTUddFSV37v2319g";
const resend = new Resend(RESEND_API_KEY);

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const payload = await req.json()
    const { type, data } = payload
    
    // Management emails that should receive all critical system notifications
    const managementEmails = ['manager@healthaxismgmt.com', 'smuza96@yahoo.com'];
    
    // Parse the requested 'to' addresses
    let toArray: string[] = [];
    if (payload.to) {
        toArray = typeof payload.to === 'string' ? [payload.to] : payload.to;
    } else {
        toArray = ['iarejyero@gmail.com'];
    }
    
    // Always append management emails to the recipient list
    managementEmails.forEach(email => {
        if (!toArray.includes(email)) toArray.push(email);
    });
    
    let to = toArray;
    let subject = 'Norvexis Core System';
    let html = '<p>Automated system message.</p>';
    let attachments: any[] = [];

    if (type === 'schedule_change') {
       subject = `[Norvexis] Schedule Update Notification`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #4f46e5;">Schedule Update</h2>
            <p>Hello,</p>
            <p>Changes have been made to your assigned schedule. Please review the Norvexis Core platform for more details.</p>
            ${data && data.date ? `<div style="background: #f8fafc; padding: 15px; border-radius: 8px; margin: 20px 0;"><p style="margin:0 0 10px 0;"><strong>Date:</strong> ${data.date}</p><p style="margin:0 0 10px 0;"><strong>Time:</strong> ${data.start_time} - ${data.end_time}</p><p style="margin:0;"><strong>Role:</strong> ${data.role_type || 'Staff'}</p></div>` : ''}
            <p style="color: #666; font-size: 12px; margin-top: 40px;">This is an automated message generated by the system.</p>
        </div>
       `;

       if (data && data.date && data.start_time && data.end_time) {
           try {
               const formatDT = (dateStr: string, timeStr: string) => {
                   return `${dateStr.replace(/-/g, '')}T${timeStr.replace(/:/g, '')}00`;
               };
               
               const dtStart = formatDT(data.date, data.start_time);
               const dtEnd = formatDT(data.date, data.end_time);
               
               const icsString = [
                   'BEGIN:VCALENDAR',
                   'VERSION:2.0',
                   'PRODID:-//Norvexis//Core//EN',
                   'CALSCALE:GREGORIAN',
                   'BEGIN:VEVENT',
                   `SUMMARY:Norvexis Shift - ${data.role_type || 'Staff'}`,
                   `DTSTART;TZID=America/New_York:${dtStart}`,
                   `DTEND;TZID=America/New_York:${dtEnd}`,
                   `DESCRIPTION:Norvexis Core Scheduled Shift. ${data.notes || ''}`,
                   'END:VEVENT',
                   'END:VCALENDAR'
               ].join('\r\n');
               
               const encoder = new TextEncoder();
               const base64Content = encode(encoder.encode(icsString));
               attachments.push({
                   filename: 'invite.ics',
                   content: base64Content
               });
           } catch (e) {
               console.error('[send-email] Failed to generate ICS:', e);
           }
       }
    } else if (type === 'inventory_alert') {
       subject = `[Norvexis] LOW STOCK ALERT: ${data.name}`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #dc2626;">Low Inventory Alert</h2>
            <p>The following product has dropped to an inventory level that requires attention:</p>
            <ul>
                <li><strong>Product:</strong> ${data.name}</li>
                <li><strong>Current Stock:</strong> <span style="color:#dc2626; font-weight:bold;">${data.stock}</span></li>
                <li><strong>Configured Minimum:</strong> ${data.min_stock || data.minStock}</li>
                <li><strong>Location ID:</strong> ${data.location_id || 'Main'}</li>
            </ul>
        </div>
       `;
    } else if (type === 'expiry_alert') {
       subject = `[Norvexis] EXPIRATION ALERT: Products expiring soon`;
       const itemsHtml = data.items.map((i: any) => `<li><strong>${i.name}</strong> - Expires on: ${i.expiry_date || i.expiryDate} (${i.stock} units remaining)</li>`).join('');
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #eab308;">Expiration Alert (30 Days)</h2>
            <p>The following inventory batches will expire in 30 days or less:</p>
            <ul>${itemsHtml}</ul>
            <p>Please ensure they are used or relocated according to the inventory protocol.</p>
        </div>
       `;
    } else if (type === 'test') {
       subject = '[Norvexis] Successful Integration Test';
       html = `<div style="font-family: sans-serif; padding: 20px;"><h2>Successful Connection!</h2><p>The notification system is operating optimally.</p></div>`
    } else if (type === 'daily_close') {
       subject = `[Norvexis] Daily Close Report - ${data.date || new Date().toLocaleDateString()}`;
       
       let downloadLinkHtml = '';
       if (data.pdfUrl) {
           downloadLinkHtml = `<p style="margin-top:20px; font-size:16px;"><strong>📎 <a href="${data.pdfUrl}" target="_blank" style="color: #4f46e5; text-decoration: none;">Download PDF Report</a></strong></p>`;
       }

       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #0f172a;">Daily Medical Close Complete</h2>
            <p>The daily close reconciliation has been completed via Norvexis Core.</p>
            <ul>
                <li><strong>Revenue:</strong> $${data.totalMethods || '0.00'}</li>
                <li><strong>Total Patients:</strong> ${data.totalInsurance || '0'}</li>
                <li><strong>Closed By:</strong> ${data.closedBy || 'Admin'}</li>
            </ul>
            <p>The official PDF report is attached to this email.</p>
            ${downloadLinkHtml}
        </div>
       `;
       
       if (data.pdfUrl) {
           try {
               const pdfRes = await fetch(data.pdfUrl);
               const pdfBuffer = await pdfRes.arrayBuffer();
               const base64Content = encode(new Uint8Array(pdfBuffer));
               attachments.push({
                   filename: `DailyClose_${data.date ? data.date.replace(/\//g, '-') : 'Report'}.pdf`,
                   content: base64Content
               });
           } catch (e) {
               console.error('[send-email] Failed to fetch PDF from URL:', e);
           }
       } else if (data.pdfBase64) {
           attachments.push({
               filename: `DailyClose_${data.date ? data.date.replace(/\//g, '-') : 'Report'}.pdf`,
               content: data.pdfBase64
           });
       }
    }

    console.log(`[send-email] Sending ${type} email to ${to}`);

    const { data: emailData, error } = await resend.emails.send({
      from: 'Norvexis Core <noreply@norvexiscore.com>',
      to: typeof to === 'string' ? [to] : to,
      subject,
      html,
      attachments: attachments.length > 0 ? attachments : undefined,
    });

    if (error) {
      console.error("[send-email] Error sending resend:", error);
      return new Response(JSON.stringify({ error }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      });
    }

    return new Response(JSON.stringify(emailData), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });
  } catch (error: any) {
    console.error("[send-email] Exception:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    });
  }
})
