import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { Resend } from 'npm:resend'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const RESEND_API_KEY = "re_6H9Qq4rL_8U485mAfZTUddFSV37v2319g";
const resend = new Resend(RESEND_API_KEY);

serve(async (req: Request) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const payload = await req.json()
    const { type, data } = payload
    
    // Default fallback
    let to = payload.to || 'iarejyero@gmail.com';
    let subject = 'Norvexis Core System';
    let html = '<p>Automated system message.</p>';
    let attachments: any[] = [];

    if (type === 'schedule_change') {
       subject = `[Norvexis] Schedule Update Notification`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #4f46e5;">Schedule Update</h2>
            <p>Hello,</p>
            <p>Changes have been made to your assigned schedule. Please review the Norvexis Core platform for more details.</p>
            <p style="color: #666; font-size: 12px; margin-top: 40px;">This is an automated message generated by the system.</p>
        </div>
       `;
    } else if (type === 'inventory_alert') {
       subject = `[Norvexis] LOW STOCK ALERT: ${data.name}`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #dc2626;">Low Inventory Alert</h2>
            <p>The following product has dropped to an inventory level that requires attention:</p>
            <ul>
                <li><strong>Product:</strong> ${data.name}</li>
                <li><strong>Current Stock:</strong> <span style="color:#dc2626; font-weight:bold;">${data.stock}</span></li>
                <li><strong>Configured Minimum:</strong> ${data.min_stock || data.minStock}</li>
                <li><strong>Location ID:</strong> ${data.location_id || 'Main'}</li>
            </ul>
        </div>
       `;
    } else if (type === 'expiry_alert') {
       subject = `[Norvexis] EXPIRATION ALERT: Products expiring soon`;
       const itemsHtml = data.items.map((i: any) => `<li><strong>${i.name}</strong> - Expires on: ${i.expiry_date || i.expiryDate} (${i.stock} units remaining)</li>`).join('');
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #eab308;">Expiration Alert (30 Days)</h2>
            <p>The following inventory batches will expire in 30 days or less:</p>
            <ul>${itemsHtml}</ul>
            <p>Please ensure they are used or relocated according to the inventory protocol.</p>
        </div>
       `;
    } else if (type === 'test') {
       subject = '[Norvexis] Successful Integration Test';
       html = `<div style="font-family: sans-serif; padding: 20px;"><h2>Successful Connection!</h2><p>The notification system is operating optimally.</p></div>`
    } else if (type === 'daily_close') {
       subject = `[Norvexis] Daily Close Report - ${data.date || new Date().toLocaleDateString()}`;
       html = `
        <div style="font-family: sans-serif; padding: 20px;">
            <h2 style="color: #0f172a;">Daily Medical Close Complete</h2>
            <p>The daily close reconciliation has been completed via Norvexis Core.</p>
            <ul>
                <li><strong>Revenue:</strong> $${data.totalMethods || '0.00'}</li>
                <li><strong>Total Patients:</strong> ${data.totalInsurance || '0'}</li>
                <li><strong>Closed By:</strong> ${data.closedBy || 'Admin'}</li>
            </ul>
            <p>The official PDF report is attached to this email.</p>
        </div>
       `;
       if (data.pdfBase64) {
           attachments.push({
               filename: `DailyClose_${data.date || 'Report'}.pdf`,
               content: data.pdfBase64
           });
       }
    }

    console.log(`[send-email] Sending ${type} email to ${to}`);

    const { data: emailData, error } = await resend.emails.send({
      from: 'Norvexis Core <noreply@norvexiscore.com>',
      to: typeof to === 'string' ? [to] : to,
      subject,
      html,
      attachments: attachments.length > 0 ? attachments : undefined,
    });

    if (error) {
      console.error("[send-email] Error sending resend:", error);
      return new Response(JSON.stringify({ error }), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      });
    }

    return new Response(JSON.stringify(emailData), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 200,
    });
  } catch (error: any) {
    console.error("[send-email] Exception:", error.message);
    return new Response(JSON.stringify({ error: error.message }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      status: 400,
    });
  }
})
